# Generated by Django for demo_206 color grid app.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='GridCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveSmallIntegerField(db_index=True)),
                ('col_index', models.PositiveSmallIntegerField(db_index=True)),
                ('color_hex', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'db_table': 'grid_cell',
                'ordering': ['row_index', 'col_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='gridcell',
            constraint=models.UniqueConstraint(fields=('row_index', 'col_index'), name='grid_cell_row_col_unique'),
        ),
    ]
