# TiDB Cluster on AWS EKS via TiDB Operator
# Minimal topology for lab: 3 PD, 3 TiKV, 2 TiDB
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: tidb-demo
spec:
  version: v<TIDB_VERSION>
  timezone: UTC
  pvReclaimPolicy: Delete
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  discovery: {}
  helper:
    image: alpine:3.16.0
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: az
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 0
    replicas: 3
    nodeSelector:
      dedicated: pd
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: pd
    storageClassName: gp2
    requests:
      storage: "20Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    evictLeaderTimeout: 1m
    replicas: 3
    nodeSelector:
      dedicated: tikv
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: tikv
    storageClassName: gp2
    requests:
      storage: "50Gi"
    config:
      storage:
        reserve-space: "0MB"
      rocksdb:
        max-open-files: 1024
      raftdb:
        max-open-files: 1024
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 0
    replicas: 2
    nodeSelector:
      dedicated: tidb
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: tidb
    storageClassName: gp2
    requests:
      storage: "20Gi"
    service:
      type: ClusterIP
    config: {}
  tiflash:
    baseImage: pingcap/tiflash
    maxFailoverCount: 0
    replicas: 1
    nodeSelector:
      dedicated: tiflash
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: tiflash
    storageClaims:
      - resources:
          requests:
            storage: 100Gi
